# Generated by Django 5.2.8 on 2025-11-26 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vioApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incident',
            name='urgency_level',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
